### PR TITLE
Fix concurrent iteration

### LINKED ISSUE #81: Cannot iterate over the same table
This is a side-effect of #80 being reported, but because iteration over tables causes the table's iterationKeys field to be assigned, it is not currently possible to perform nested iteration over the same table. For example, the following test will fail (but it will pass in regular Lua 5.2):

```go
func TestConcurrentNext(t *testing.T) {
	testString(t, `
	t = {}
	t[1], t[2], t[3] = true, true, true

	r = {}
	for k1 in pairs(t) do
		r[#r + 1] = k1
		for k2 in pairs(t) do
			r[#r + 1] = k2
		end
	end

	got = table.concat(r, "")
	want = "112321233123"
	assert(got == want, "got " .. got .. "; want " .. want)
	`)
}
```

### PR DESCRIPTION
**Pull request by fbogsany**
Fixes #81 

r: @nilium

### CODE REVIEW

File: tables.go [hunk 1]
```diff
@@ -87,7 +94,7 @@ func (t *table) putAtInt(k int, v value) {
 	} else if v == nil {
 		delete(t.hash, float64(k))
 	} else {
-		t.hash[float64(k)] = v
+		t.addOrInsertInMap(float64(k), v)
```
Comment (shivnagarajan) [inline tables.go]: Could we not call this `addOrInsertHash` to keep the language similar to `delete(t.hash...)` not really picky here..

**Comment by fbogsany** [comment]
This leaks keys, since we don't modify the `t.iterationKeys` on `delete` from `t.hash`. We can probably deal with this by sorting the `t.iterationKeys`, then binary searching for a key and removing it from the slice on `delete`. It's not especially performant - we're trading space for performance here.

**Comment by nilium** [comment]
That seems like it should work and account for `next` behavior (i.e., should work fine over deleted keys). At least if a key is removed, the binary search will identify its expected location and resume from there. I agree that performance isn't fantastic for this, but in the worst case, the map could be replaced by porting Lua's table structure from C. (It could be optimized by breaking the keyset up into buckets, but then it's necessary to work out hashing and so on, which isn't great -- doable, given the limited types, but not great.)

File: tables.go [hunk 2]
```diff
@@ -241,15 +247,17 @@ func (l *State) next(t *table, key int) bool {
 		t.iterationKeys = keys
 	}
 	found := k == nil
-	for _, hk := range t.iterationKeys {
-		if found {
+	for i, hk := range t.iterationKeys {
+		if hk == nil { // skip deleted key
+		} else if _, present := t.hash[hk]; !present {
+			t.iterationKeys[i] = nil // mark key as deleted
```
Comment (fbogsany) [inline tables.go]: This removes references to deleted keys during iteration. It's not a perfect solution, since building a table, iterating over it, and nulling out all the entries will leak the keys as long as a reference exists to the table, if we never iterate over it again. It's a lot cheaper than sorting and searching, though, and much easier to implement (not least because we can't sort the keys in the general case).

Comment (shivnagarajan) [inline tables.go]: This looks like a reasonable compromise. 👍
